services:
  studeehub.api:
    env_file:
       - stack.env
    image: ${DOCKER_REGISTRY-}studeehubapi
    build:
      context: .
      dockerfile: studeehub.API/Dockerfile
    ports:
     - "5000:8080"
     - "5001:8081"
